# Generated by Django 4.0.3 on 2022-06-16 09:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_burgers_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='burgers',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='burgers', to='product.category'),
        ),
        migrations.AlterField(
            model_name='burgers',
            name='image',
            field=models.ImageField(default='', null=True, upload_to='burgers'),
        ),
        migrations.AlterField(
            model_name='burgers',
            name='name_en',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='burgers',
            name='name_ru',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
