# Generated by Django 4.0.3 on 2022-08-05 09:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0006_delete_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Filial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(blank=True, max_length=300, null=True)),
                ('phone', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_time', models.DateTimeField(auto_now_add=True)),
                ('delivery', models.CharField(choices=[('Dostavka', 'Доставка'), ('Samovizov', 'Самовывоз')], max_length=20)),
                ('payment_type', models.CharField(choices=[('click', 'Click'), ('payme', 'Payme'), ('nalichniy', 'Наличные')], max_length=20)),
                ('address', models.CharField(max_length=300, null=True)),
                ('kvartira', models.IntegerField(blank=True, null=True)),
                ('podyezd', models.IntegerField(blank=True, null=True)),
                ('etaj', models.IntegerField(blank=True, null=True)),
                ('location', models.CharField(max_length=200)),
                ('user', models.ForeignKey(default=0, on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(default=1)),
                ('product_price', models.FloatField()),
                ('filial', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.filial')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.orders')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.burgers')),
            ],
        ),
    ]
