# Generated by Django 4.0.3 on 2022-08-07 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_remove_orders_etaj_remove_orders_podyezd_orders_dom_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='location',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
