# Generated by Django 4.0.3 on 2022-08-07 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_rename_product_price_orderdetail_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='filial',
            name='work_time',
            field=models.CharField(default='', max_length=100),
        ),
    ]
