# Generated by Django 4.0.3 on 2022-08-07 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_filial_work_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filial',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
