# Generated by Django 4.0.3 on 2022-08-08 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_alter_orderdetail_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
